---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
# verifier:
#   name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    - verify
    - destroy
verifier:
  name: ansible
  enabled: true
  lint:
    name: ansible-lint
# lint: ansible-lint
lint: |
  ansible-lint -x 301
